### ISSUE TITLE
Problem when exiting minimized DDO-ML

### ISSUE THREAD

**Issue by inedarr** [traversc/DDO-ML#6]
1) launch DDO-ML normally
2) minimize it's window into taskbar
3) while minimized, exit DDO-ML by using right mouse button menu on the tray icon.
After this, the saved ddo-ml.ini will contain impossible window coordinates like both X and Y set to -32000. The next time you launch DDO-ML the window won't show up at all. I keep a backup of ini file with proper values just in case. This happens on Windows 7. No idea about Win 10. Making sure the window is visible before exiting will probably avoid the problem.

**Comment by traversc** [comment]
You might want to try pinging MIvanisten (https://github.com/MIvanisten) here or on forums (same name I think).  

I'm guessing it's because your game resolution is different than your desktop resolution.  

I don't play this game anymore or program in autoIt.  If he doesn't respond, I can give it a shot.

**Comment by MIvanIsten** [comment]
Fixed in v1.5.0.0
